[package]
name = "ima_adpcm_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"
jni = "0.20.0"

[profile.release]
lto = true
incremental = false

[lib]
crate_type = ["cdylib"]
name = "ima_adpcm_rs64"

